### PR TITLE
FEATURE: Add support for forking simple package from the Neos organization

### PR DESCRIPTION
**Pull request by dfeyer**
This change add support to fork simple package like Neos.SEO or TYPO3.Party to make life easier to new contributor.

### CODE REVIEW

**Comment by dfeyer** [comment]
Contains some bug, will push an update

**Comment by dfeyer** [comment]
:+1: ready for test, not sure why it's has conflict ... rebase on master but no change :(

**Comment by dfeyer** [comment]
And sorry for the boyscooting ... but you know when you start boyscouting ...

**Comment by kdambekalns** [comment]
I'd rather install `hub` and do a `hub fork`… ;)

**Comment by kdambekalns** [comment]
Closing this, since `hub fork` does the same for any GH repo, is maintained by others, and this one has been lying here since last year… :)

**Pull request closed without merging**
